### ISSUE TITLE
JWT needs to track user ID

### ISSUE THREAD

**Issue by jakelong95** [jakelong95/TownCenter#13]
When creating a JWT for a user, it needs to keep track of that user's ID so we can ensure a user is only trying to access their own information.

**Comment by ghmeier** [comment]
Got em. [Right Here](https://github.com/jakelong95/TownCenter/commit/e26aba1df403ffc217c22959f11dfde3061e23f7#diff-dcf41c34535ce773f63b631df112d76bR243)
