### ISSUE TITLE
Use standard Country Codes

### ISSUE THREAD

**Issue by ghmeier** [jakelong95/TownCenter#15]
Stripe requires standard country codes, so it would be nice to switch TownCenter stuff to use country codes rather than string: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements

**Comment by jakelong95** [comment]
I'm not really sure what change needs to be made here. Why not just have the front end send the country code and store that as a string?

**Comment by ghmeier** [comment]
Seems reasonable, maybe this gets added to the input validation ticket
