### ISSUE TITLE
Collect additional information for roasters

### ISSUE THREAD

**Issue by ghmeier** [jakelong95/TownCenter#16]
Roasters also need the following information:
business_name (like their official business name)
date of birth - day, month, year

**Comment by jakelong95** [comment]
Date of birth is for account holder

**Comment by jonnykry** [comment]
why would a roaster need a DOB?

**Comment by jakelong95** [comment]
Is there a specific format towncenter should return the birthday in?

**Comment by ghmeier** [comment]
MM/DD/YYYY or have them each as their own property
